Add OVN/OVS Monitor
alauda/kube-ovn pull request #499
Opened 2020-10-09 12:05 UTC by hongzhen-ma

Add Prometheus Monitor

2020-10-10 02:36 UTC, oilbeater requested changes

2020-10-10 02:36 UTC, oilbeater commented on pkg/ovn_monitor/exporter.go
> +		log.Errorf("%s failed to get system id: %s", appName, err)
这里出错要不要退出程序

2020-10-10 02:36 UTC, oilbeater commented on cmd/ovn_monitor/ovn_monitor.go
> +	err := exporter.StartConnection()
可以使用 if er:= xxx; err != nil {} 这种形式，减少行数

2020-10-10 02:36 UTC, oilbeater commented on cmd/ovn_monitor/ovn_monitor.go
> +		log.Errorf("%s failed to connect db socket properly: %s", ovn.GetExporterName(), err)
log 的地方使用 klog 和其他地方保持一致

2020-10-10 02:36 UTC, oilbeater commented on dist/images/install.sh
> +              add: ["SYS_NICE"]
yaml 比较多，修改都要同步一下

2020-10-10 02:36 UTC, oilbeater commented on pkg/ovn_monitor/exporter.go
> +			_ = e.Client.GetSystemID()
这里的错误也需要记录一下

2020-10-10 02:36 UTC, oilbeater commented on pkg/ovn_monitor/exporter.go
> +		time.Sleep(30 * time.Second)
这个时间是不是应该是 pollInterval

2020-10-10 02:36 UTC, oilbeater commented on pkg/pinger/ping.go
> +			e.ovsMetricsUpdate()
job 模式下不需要收集 metrics，可以用 kubectl ko diagnose all 看一下是否按预期工作

2020-10-14 08:22 UTC, hongzhen-ma commented on cmd/ovn_monitor/ovn_monitor.go
> +	var listenAddress string
已经修改，增加config文件

2020-10-14 08:22 UTC, hongzhen-ma commented on dist/images/install.sh
> +              add: ["SYS_NICE"]
已经排查删除该权限

2020-10-14 08:23 UTC, hongzhen-ma commented on dist/images/install.sh
> +      targetPort: 9999
修改为10661端口

2020-10-14 08:23 UTC, hongzhen-ma commented on pkg/ovn_monitor/exporter.go
> +		log.Errorf("%s failed to get system id: %s", appName, err)
看了下这个地方不需要退出，在别的逻辑中还会重新获取这个参数取值

2020-10-14 08:23 UTC, hongzhen-ma commented on cmd/ovn_monitor/ovn_monitor.go
> +	err := exporter.StartConnection()
已经排查修改

2020-10-14 08:23 UTC, hongzhen-ma commented on cmd/ovn_monitor/ovn_monitor.go
> +		log.Errorf("%s failed to connect db socket properly: %s", ovn.GetExporterName(), err)
已经修改

2020-10-14 08:24 UTC, hongzhen-ma commented on pkg/ovn_monitor/exporter.go
> +		time.Sleep(30 * time.Second)
已经修改

2020-10-14 08:24 UTC, hongzhen-ma commented on pkg/ovn_monitor/exporter.go
> +			_ = e.Client.GetSystemID()
补充了错误处理

2020-10-14 09:08 UTC, oilbeater approved these changes

2020-10-14 10:56 UTC, merged