update review problems for ovn_monitor
alauda/kube-ovn pull request #517
Opened 2020-10-22 10:25 UTC by hongzhen-ma

2020-10-22 12:38 UTC, oilbeater commented on pkg/ovnmonitor/metric.go
> +			Help:      "The size of a log file associated with an OVN component. The unit is Bytes.",
name 改成 log_file_size_bytes

还有 pinger 里对应的指标名字也要改一下

2020-10-23 01:35 UTC, hongzhen-ma commented on pkg/ovnmonitor/metric.go
> +			Help:      "The size of a log file associated with an OVN component. The unit is Bytes.",
已经修改提交

2020-10-23 01:57 UTC, oilbeater requested changes

2020-10-23 01:57 UTC, oilbeater commented on dist/images/install.sh
> +      shareProcessNamespace: true
install-pre-1.16.sh 和 yaml 目录下手动部署使用的 yaml 那里也需要修改一下

2020-10-23 03:27 UTC, hongzhen-ma commented on dist/images/install.sh
> +      shareProcessNamespace: true
已经修改

2020-10-23 03:33 UTC, oilbeater approved these changes

2020-10-23 03:45 UTC, merged