feature: custom vpc
alauda/kube-ovn pull request #524
Opened 2020-10-25 03:22 UTC by fanriming

Support custom VPC by the annotation 'ovn.kubernetes.io/vpc_name', remain the cluster VPC as the default VPC.
Custom VPC not support lb/dns/underlay yet.

2020-10-26 01:45 UTC, oilbeater commented
@fanriming 把 vpc 当成一个单独的 CRD 提出来？这样可以统一管理 logical router 现在的方式 vpc 的管理有些分散，之后 vpc 级别的配置也可以在这个 crd 里统一管理

2020-10-26 02:52 UTC, fanriming commented
> @fanriming 把 vpc 当成一个单独的 CRD 提出来？这样可以统一管理 logical router 现在的方式 vpc 的管理有些分散，之后 vpc 级别的配置也可以在这个 crd 里统一管理

CRD确实会更清晰些，我再看看

2020-11-02 03:22 UTC, oilbeater requested changes

2020-11-02 03:22 UTC, oilbeater commented on pkg/apis/kubeovn/v1/types.go
> +	Namespaces []string `json:"namespaces,omitempty"`
vpc 可以直接和 subnets 关联，不需要再跳一层去关联 namespace了

2020-11-02 03:22 UTC, oilbeater commented on pkg/apis/kubeovn/v1/types.go
> +	DefaultLogicalSwitch   string   `json:"defaultLogicalSwitch"`
下边这几个字段放spec里会好一些

2020-11-02 03:22 UTC, oilbeater commented on pkg/controller/controller.go
> +	c.checkVpcResourceQueue.ShutDown()
其他几个queue也需要在这里关闭

2020-11-02 03:22 UTC, oilbeater commented on pkg/controller/namespace.go
> +	var ls, cidr string
这里可以通过 ns 取出 subnet，再取 vpc，ns 直接只和 subnet 关联

2020-11-02 03:22 UTC, oilbeater commented on pkg/controller/subnet.go
> +		if sub.Name != subnet.Name && sub.Spec.Vpc == sub.Spec.Vpc && util.CIDRConflict(sub.Spec.CIDRBlock, subnet.Spec.CIDRBlock) {
sub.Spec.Vpc == sub.Spec.Vpc ?

2020-11-02 23:29 UTC, fanriming commented on pkg/apis/kubeovn/v1/types.go
> +	Namespaces []string `json:"namespaces,omitempty"`
这里是想通过vpc做ns的范围限制，vpc 内的 subnet 绑定的ns必须要在vpc的范围内

2020-11-02 23:37 UTC, fanriming commented on pkg/apis/kubeovn/v1/types.go
> +	DefaultLogicalSwitch   string   `json:"defaultLogicalSwitch"`
这些字段段值因为是自动生成的，外面不能改，即便放在spec也是不能自定义的，放在status好像也说的过去

2020-11-02 23:38 UTC, fanriming commented on pkg/controller/controller.go
> +	c.checkVpcResourceQueue.ShutDown()
Got it.

2020-11-02 23:40 UTC, fanriming commented on pkg/controller/namespace.go
> +	var ls, cidr string
ns的注解改成只放subnet相关信息了

2020-11-02 23:47 UTC, fanriming commented on pkg/controller/subnet.go
> +		if sub.Name != subnet.Name && sub.Spec.Vpc == sub.Spec.Vpc && util.CIDRConflict(sub.Spec.CIDRBlock, subnet.Spec.CIDRBlock) {
我改一下，应该一个是sub一个是subnet

2020-11-03 03:14 UTC, oilbeater approved these changes

2020-11-04 03:51 UTC, oilbeater commented
@fanriming `pkg/controller/init.go` 和 master 分支有冲突，需要 rebase 一下 master 解决冲突

2020-11-04 07:35 UTC, fanriming commented
> @fanriming `pkg/controller/init.go` 和 master 分支有冲突，需要 rebase 一下 master 解决冲突
冲突解决了

2020-11-04 07:54 UTC, merged

2020-11-04 07:54 UTC, oilbeater commented
Great work! Thanks @fanriming