Add adaption for dualstack, part of controller process.
alauda/kube-ovn pull request #573
Opened 2020-12-03 03:23 UTC by hongzhen-ma

Co-authored-by: feixiang43 <352447595@qq.com>

2020-12-03 07:55 UTC, oilbeater requested changes

2020-12-03 07:55 UTC, oilbeater commented on pkg/controller/node.go
> +	if util.IsValidIP(v4IP) && util.IsValidIP(v6IP) {
这个逻辑可以抽一个单独的函数，替换下面几个类似的逻辑

2020-12-03 07:55 UTC, oilbeater commented on pkg/controller/node.go
> +		if len(addresses) == 2 {
用for循环删除所有ip

2020-12-03 07:55 UTC, oilbeater commented on pkg/controller/pod.go
> +					if len(nodeTunlIPAddr) == 2 {
同样用循环

2020-12-03 07:55 UTC, oilbeater commented on pkg/util/validator.go
> +	protocol := CheckProtocol(cidr)
循环替换，不用区分双栈，切分后所有都检查

2020-12-03 07:55 UTC, oilbeater commented on pkg/util/net.go
> +			if CheckProtocol(cidrBlocks[0]) != CheckProtocol(ips[0]) || CheckProtocol(cidrBlocks[1]) != CheckProtocol(ips[1]) {
应该不存在双栈下两个协议都不匹配

2020-12-03 07:55 UTC, oilbeater commented on pkg/util/net.go
> +			if CheckProtocol(cidrBlocks[0]) != CheckProtocol(ipStr) && CheckProtocol(cidrBlocks[1]) != CheckProtocol(ipStr) {
同上

2020-12-03 07:55 UTC, oilbeater commented on pkg/ipam/ipam.go
> +		v4IP, v6IP, mac, protocol := subnet.GetPodAddress(podName)
函数替换

2020-12-03 07:55 UTC, oilbeater commented on pkg/controller/node.go
> +	if util.IsValidIP(v4IP) && util.IsValidIP(v6IP) {
函数替换

2020-12-03 07:55 UTC, oilbeater commented on pkg/controller/subnet.go
> +	if subnet.Spec.Protocol == kubeovnv1.ProtocolDual {
循环替换

2020-12-03 09:26 UTC, hongzhen-ma commented on pkg/controller/node.go
> +	if util.IsValidIP(v4IP) && util.IsValidIP(v6IP) {
已经修改

2020-12-03 09:26 UTC, hongzhen-ma commented on pkg/controller/node.go
> +	if util.IsValidIP(v4IP) && util.IsValidIP(v6IP) {
已经修改

2020-12-03 09:26 UTC, hongzhen-ma commented on pkg/controller/node.go
> +		if len(addresses) == 2 {
已经修改

2020-12-03 09:26 UTC, hongzhen-ma commented on pkg/controller/pod.go
> +					if len(nodeTunlIPAddr) == 2 {
已经修改

2020-12-03 09:27 UTC, hongzhen-ma commented on pkg/controller/subnet.go
> +	if subnet.Spec.Protocol == kubeovnv1.ProtocolDual {
已经修改

2020-12-03 09:27 UTC, hongzhen-ma commented on pkg/util/net.go
> +			if CheckProtocol(cidrBlocks[0]) != CheckProtocol(ips[0]) || CheckProtocol(cidrBlocks[1]) != CheckProtocol(ips[1]) {
删除了这个检查

2020-12-03 09:28 UTC, hongzhen-ma commented on pkg/util/net.go
> +			if CheckProtocol(cidrBlocks[0]) != CheckProtocol(ipStr) && CheckProtocol(cidrBlocks[1]) != CheckProtocol(ipStr) {
删除了这个检测

2020-12-03 09:28 UTC, hongzhen-ma commented on pkg/util/validator.go
> +	protocol := CheckProtocol(cidr)
已经修改

2020-12-03 10:00 UTC, hongzhen-ma commented on pkg/ipam/ipam.go
> +		v4IP, v6IP, mac, protocol := subnet.GetPodAddress(podName)
看了下GetPodAddress这个函数的调用，是属于比较底层的调用了，这块感觉没必要再抽出来一个函数。

2020-12-04 02:17 UTC, oilbeater requested changes

2020-12-06 06:19 UTC, hongzhen-ma commented on pkg/controller/pod.go
> +	ips := strings.Split(nodeTunlIP, ",")
已经修改

2020-12-07 05:27 UTC, oilbeater approved these changes

2020-12-07 05:33 UTC, merged