Add adaption for dualstack, part of daemon process.
alauda/kube-ovn pull request #577
Opened 2020-12-07 05:55 UTC by hongzhen-ma

Co-authored-by: feixiang43 <352447595@qq.com>

2020-12-07 07:37 UTC, oilbeater requested changes

2020-12-07 07:37 UTC, oilbeater commented on pkg/daemon/gateway.go
> +		protocols = append(protocols, kubeovnv1.ProtocolIPv4, kubeovnv1.ProtocolIPv6)
直接赋值就可以，不需要 append

2020-12-07 07:37 UTC, oilbeater commented on pkg/daemon/ovs.go
> +	ipAddMap := make(map[string]netlink.Addr)
什么情况下会需要删除 ip

2020-12-09 09:25 UTC, hongzhen-ma commented on pkg/daemon/gateway.go
> +		protocols = append(protocols, kubeovnv1.ProtocolIPv4, kubeovnv1.ProtocolIPv6)
修改了

2020-12-09 09:27 UTC, hongzhen-ma commented on pkg/daemon/ovs.go
> +	ipAddMap := make(map[string]netlink.Addr)
这块代码参考了feixiang的实现。代码逻辑上应该是先检查下接口有没有配置地址，有的话是先删除掉，再重新配置新地址。
实际测试的时候，打印出来ipDelMap看了下，是空的值

2020-12-09 10:16 UTC, oilbeater approved these changes

2020-12-10 05:28 UTC, merged