modify static gw changed problem
alauda/kube-ovn pull request #637
Opened 2021-01-08 03:31 UTC by hongzhen-ma

2021-01-08 06:04 UTC, oilbeater requested changes

2021-01-08 06:04 UTC, oilbeater commented on pkg/util/net.go
> +			var gwArray []string
下面两个分支是一样的，
`gws = append(gws, gateway)` 是不是就可以了

2021-01-11 09:00 UTC, hongzhen-ma commented on pkg/util/net.go
> +			var gwArray []string
顺序不一致，根据原协议类型，区分顺序添加，能保证 IPv4,IPv6的顺序

2021-01-11 09:26 UTC, hongzhen-ma commented on pkg/util/net.go
> +			var gwArray []string
已修改

2021-01-11 09:43 UTC, oilbeater approved these changes

2021-01-11 09:47 UTC, merged